### ISSUE TITLE
ConnectionListener is being triggered twice upon disconnect

### ISSUE THREAD

**Issue by foroughgoudarzi** [OpenHFT/Chronicle-Network#218] opened 2022-10-26 10:01 UTC

**Comment by RobAustin** [comment] 2022-10-26 10:03
I suspect this is being caused by the heartbeat handler also triggering an onDisconnect, I question if it is necessary for the heartbeat handler to be registered as a connection listener

**Comment by JerryShea** [comment] 2022-10-26 22:05
Duplicate of #164?

**Comment by nicktindall** [comment] 2022-10-26 22:14
This is a duplicate of #164, will close it

**Closed as not planned** 2022-10-26 22:15 UTC
Labels: duplicate
